CREATE TABLE SOCIOUNICO.TASUFOLIOS_HON
										(
											 FIFOLIO_ID 	        NUMBER
											,FICASO_ID  	        NUMBER
											,FCFECHA_CREACION       VARCHAR2(50)
											,FCFECHA_ASIGNACION     VARCHAR2(50)
											,FCTICKET_TIPO          VARCHAR2(50)
											,FCDESCRIPCION 		    VARCHAR2(50)
											,FCDESCRIPCION2		    VARCHAR2(50)
											,FCAREA_ASIG			VARCHAR2(50)
											,FCESTATUS				VARCHAR2(50)
											,FCRESUL_DEN			VARCHAR2(50)
											,FCFECHA_CIERRE			VARCHAR2(50)
											,FCFECHA_RESUELTO		VARCHAR2(50)
											,FCANAL_ORIGEN			VARCHAR2(50)
											,FCANONIMATO 			VARCHAR2(50)
											,FCAGENTE_ASIG 			VARCHAR2(50)
											,FCFECHA_STANDBY 		VARCHAR2(50)
											,FCATENDEDOR			VARCHAR2(50)
											,FCORREO_ATENDEDOR 		VARCHAR2(50)
											,FCESTADO				VARCHAR2(50)
											,FCREUCPERACION			VARCHAR2(50)
											,FCONCLUCIONES			VARCHAR2(50)
											,FIHORAS_INVES			NUMBER
											,FDULTIMA_MODIFICACION  DATE
											,FCUSUARIO_MODIFICO     VARCHAR2(30)
										);

	ALTER TABLE SOCIOUNICO.TASUFOLIOS_HON ADD CONSTRAINT PK_HON_01 PRIMARY KEY (FIFOLIO_ID);


	CREATE TABLE SOCIOUNICO.TASUDENUNXFOL_HON
											(
												 FIFOLIO_ID				NUMBER
												,FIDENUN_ID 			NUMBER
												,FINUNDENUN_ID			NUMBER
												,FCNOMBRE_DENUNCIADO	VARCHAR2(100)
												,FCPUESTO_DENUNCIADO 	VARCHAR2(100)
												,FCOMPANIA_DENUNCIADO 	VARCHAR2(70)
												,FCUBICA_DENUNCIADO 	VARCHAR2(50)
												,FCESTADO_DENUNCIADO 	VARCHAR2(50)
												,FCDEPART_DENUNCIADO	VARCHAR2(50)
												,FCREPONSABLE_DENUN	 	VARCHAR2(50)
												,FDULTIMA_MODIFICACION  DATE
												,FCUSUARIO_MODIFICO		VARCHAR2(50)
											);

	ALTER TABLE SOCIOUNICO.TASUDENUNXFOL_HON ADD CONSTRAINT PK_HON_02 PRIMARY KEY (FIFOLIO_ID,FIDENUN_ID);
	ALTER TABLE SOCIOUNICO.TASUDENUNXFOL_HON ADD CONSTRAINT FK_HON_01 FOREING KEY (FIFOLIO_ID) REFERENCES SOCIOUNICO.TASUFOLIOS_HON;


	CREATE TABLE SOCIOUNICO.TASUDENUNCT_HON
											(
												FIFOLIO_ID      	 	NUMBER
											   ,FISOCIO_DENUNCIANTE	 	NUMBER
											   ,FCNOMBRE_DENUNCIANTE 	VARCHAR2(50)
											   ,FCPUESTO_DENUNCIANTE	VARCHAR2(50)
											   ,FCORREO_DENUNCIANTE		VARCHAR2(50)
											   ,FCTEL_DENUNCIANTE		VARCHAR2(50)
											   ,FCDEPART_DENUNCIANTE	VARCHAR2(50)
											   ,FICONTAC_DENUNCIANTE	VARCHAR2(50)
											   ,FCMEDIOCONT_DENUNCIANTE	VARCHAR2(50)
											   ,FCHALLAZGO_DENUNCIANTE	VARCHAR2(50)
											   ,FDULTIMA_MODIFICACION	DATE
											   ,FCUSUARIO_MODIFICO		VARCHAR2(50)

											);

											CREATE TABLE SOCIOUNICO.TASUINVOLU_HON (
    FIFOLO_ID           NUMBER PRIMARY KEY,
    FINVOLUCRADO_ID     NUMBER,
    FINVOLUCRADO_DESC   VARCHAR2(4000 BYTE),
    FDULTIMA_MODIFICACION DATE,
    FCUSUARIO_MODIFICO  VARCHAR2(30 BYTE),
    FCNOMBRE_INVOLUCRADO VARCHAR2(80 BYTE),
    FCPUESTO_INVOLUCRADO VARCHAR2(110 BYTE),
    FCCOMPANIA_INVOLUCRADO VARCHAR2(80 BYTE),
    FCHALLAZGO_1_INVOL  VARCHAR2(80 BYTE),
    FCHALLAZGO_2_INVOL  VARCHAR2(80 BYTE),
    FCONSECUENCIA_INVOL VARCHAR2(80 BYTE),
    FCRESPON_EJEC_INVOL VARCHAR2(80 BYTE),
    FCFECHA_EJEC_INVOL  VARCHAR2(80 BYTE),
    FCNIVEL_MANDO_INVOL VARCHAR2(110 BYTE),
    CONSTRAINT PKTA69_P PRIMARY KEY (FIFOLO_ID, FINVOLUCRADO_ID),
    CONSTRAINT FKT69_F1 FOREIGN KEY (FIFOLO_ID) REFERENCES OTRA_TABLA (FIFOLO_ID)
);

CREATE TABLE SOCIOUNICO.TASUFOLIOS2_HON (
    FIFOLO_ID           NUMBER PRIMARY KEY,
    FIGRAVEDAD_ID       NUMBER,
    FIURGEN_ID          NUMBER(3),
    FDULTIMA_MODIFICACION DATE,
    FCUSUARIO_MODIFICO  VARCHAR2(30 BYTE),
    CONSTRAINT PKFIFOLO_ID PRIMARY KEY (FIFOLO_ID),
    CONSTRAINT FKFIFOLO_ID FOREIGN KEY (FIFOLO_ID) REFERENCES OTRA_TABLA (FIFOLO_ID),
    CONSTRAINT FKFIGRAVEDAD_ID FOREIGN KEY (FIGRAVEDAD_ID) REFERENCES OTRA_TABLA (FIGRAVEDAD_ID),
    CONSTRAINT FKFIURGEN_ID FOREIGN KEY (FIURGEN_ID) REFERENCES OTRA_TABLA (FIURGEN_ID)
);

CREATE TABLE SOCIOUNICO.TASUTMXDNXF_HON (
    FIFOLO_ID           NUMBER PRIMARY KEY,
    FIDENUN_ID          NUMBER,
    FITEMA_ID           NUMBER,
    FCTEMA_DESC         VARCHAR2(500 BYTE),
    FCCOMP_DESC         VARCHAR2(500 BYTE),
    FDULTIMA_MODIFICACION DATE,
    FCUSUARIO_MODIFICO  VARCHAR2(30 BYTE),
    CONSTRAINT PKTA67_P PRIMARY KEY (FIFOLO_ID, FIDENUN_ID, FITEMA_ID),
    CONSTRAINT FKT67_F1 FOREIGN KEY (FIFOLO_ID) REFERENCES OTRA_TABLA (FIFOLO_ID)
);
